### ISSUE TITLE
[Effort 9] As an app user, I want to post photos, videos and opinions in a way that everyone in the event can see it, so that I share my experience with all the participants.

### ISSUE THREAD

**Issue by M4riaLoureiro** [FEUP-ESOF-2020-21/open-cx-t3g3-404datanotfound#16]
[Mockup New Post](https://github.com/FEUP-ESOF-2020-21/open-cx-t3g3-404datanotfound/blob/main/docs/MockupImages/NewPost.png)

**Scenario**: Post on the event's feed
  **Given** there are 3 posts on the feed
  **When** I tap the "Plus" button
  **And** enter content (text, photo and video)
  **And** I tap the "Post" button
  **Then** there should appear 4 posts on the feed

**Comment by JoaoCarlosPires** [comment]
Our app is unable to play videos, but, for the scope of ESOF, we think this User Story is completed in the majority.
