### ISSUE TITLE
[Effort 5] As an app user, I want to see the list of all the conference participants, so that I can know who is also attending the conference.

### ISSUE THREAD

**Issue by joamats** [FEUP-ESOF-2020-21/open-cx-t3g3-404datanotfound#49]
[Mockup Participants List](https://github.com/FEUP-ESOF-2020-21/open-cx-t3g3-404datanotfound/blob/main/docs/MockupImages/SeeAllParticipants.png)

**Scenario**: Access participants' list
  **Given** I am on the event feed
  **When** I tap the "Participants" button
  **Then** a list with all participants should appear

**Comment by JoaoCarlosPires** [comment]
Completely done!
